minimumReleaseAgeExclude:
  - ajv@6.12.3 || 6.14.0
  - cross-spawn@6.0.6
  - tmp@0.2.4 || 0.2.6
  - brace-expansion@5.0.8
overrides:
  ajv@<6.12.3: ^6.12.3
  ajv@<6.14.0: ^6.14.0
  brace-expansion@<=5.0.7: ^5.0.8
  cross-spawn@<6.0.6: ^6.0.6
  tmp@<0.2.6: ^0.2.6
  tmp@<=0.2.3: ^0.2.4
